### ISSUE TITLE
Проблема с мультиархивами

### ISSUE THREAD

**Issue by SileNTViP** [adm244/AGSUnpacker#1]
Привет.
Есть проблема с мультиархивами, если файлы хранятся не только в основном архиве. Для этого у вас есть assetInfos.UId где хранится индекс архива. А вот названия архивов как раз в lib_filenames. При распаковке нужно сверять UId и открывать нужный файл из lib_filenames.

**Comment by adm244** [comment]
Старый класс AGSClibUtils действительно не умеет работать с мультиархивами, в будущем планируется его полностью убрать. Ему на замену пришел класс AssetsManager, который как раз умеет работать с мультиархивами.

P.s. В последнее время не обновляю репозиторий, все мелкие изменения держатся локально и делаются по мере необходимости, когда нужно ковырнуть очередную игру.

**Comment by adm244** [comment]
В версии 06 проблема с мультиархивами решена.
