### ISSUE TITLE
Unable to unpack game made with AGS 3.6.0.54

### ISSUE THREAD

**Issue by arcanetrivia** [adm244/AGSUnpacker#6]
The notes for v.07 say it supports AGS 3.6.0, but I was not able to unpack a game built with 3.6.0.54, receiving an error message that the exe was not a valid AGS game. Is that too new of a sub-version for AGSUnpacker to handle? If so will the program be updated? (I was able to successfully unpack a game made with AGS version 3.4.1-something.)

**Comment by adm244** [comment]
Can you verify if this is still valid for [AGSUnpacker v08](https://github.com/adm244/AGSUnpacker/releases/tag/v08)?

If v08 doesn't solve this problem then specify which game you're trying this on and its version also.

**Comment by arcanetrivia** [comment]
After four months, I'm not entirely certain what game it was I was even trying to unpack anymore 😅 But if I'm right by matching the dates of certain files on my computer, this version of AGSUnpacker works on the game in question and I was able to get the text .trs file out of it. That was Stair Quest Winter 2023 version https://decafjedi.itch.io/stair-quest

**Comment by adm244** [comment]
Ok, I guess we can close this issue now 😃

**Comment by rofl0r** [comment]
where can one get the winter '23 version of that? i downloaded the current linux version and the engine says: `Compiled with: 3.4.0.12`

**Comment by adm244** [comment]
@rofl0r "Stair Quest: Winter 2023 Edition (Windows)" from itch io page is using 3.6.0.54 engine.

**Comment by rofl0r** [comment]
oh, right, thanks. i can see it now :p
